name: Codacy Coverage Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Create Coverage File
      run: go test ./... -race -v -covermode atomic -coverprofile=covprofile ./...
    
    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest
    
    - name: Send Coverage Codacy
      run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report \ --force-coverage-parser go -r covprofile --project-token ${{ secrets.CODACY_PROJECT_TOKEN }}
